apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transactionservice
  name: transactionservice
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: transaction
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - image: anithait/transaction-service:0.0.1-RELEASE
        imagePullPolicy: IfNotPresent
        name: transaction
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
      restartPolicy: Always    
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: transaction
  name: transaction
  namespace: default
spec:
  ports:
  - 
    port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    app: transaction
  sessionAffinity: None
  type: LoadBalancer


